- hosts: all
  become: yes
  tasks:
  - name: remove password authentication and permit root login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '{{item.From}}' 
      line:  '{{item.To}}'
      state: present
    loop: 
      - { From: '^PasswordAuthentication', To: 'PasswordAuthentication no'}
      - { From: '^PermitRootLogin', To: 'PermitRootLogin no'}

  - name: restart sshd process
    systemd:
      name: sshd.service
      state: restarted
  - name: populate sshd process status
    service_facts:
  - name: check sshd process status
    debug:
      var: ansible_facts.services["sshd.services"]